from __future__ import annotations

import json
import sqlite3
import time
from pathlib import Path
from typing import Any


def utc_ms() -> int:
    return int(time.time() * 1000)


# Source-of-fault classification. The whole point: when something is red in the
# dashboard, you instantly know WHOSE problem it is — a test harness (ignore),
# the caller/mod (bad request), Player2/the model (upstream), or our bridge code.
_TEST_MOD_MARKERS = ("smoke", "stress", "grounded", "event_queue", "probe", "demo")
_CLIENT_ERROR_MARKERS = (
    "unsafe characters", "invalid json", "invalid request", "contract",
    "required", "invalid request size", "missing", "must be",
)
_UPSTREAM_ERROR_MARKERS = (
    "no text content", "no usable text", "timed out", "connection failed",
    "connection refused", "player2 http", "could not reach a usable ai",
    "npc returned no message", "player2 request timed out", "player2 connection",
)


def classify_source(status: str | None, error: str | None, source_mod: str | None = None) -> str:
    """Return one of: ok | test | client | upstream | bridge.

    - test     : generated by a built-in test/stress harness (not real traffic)
    - client   : the caller sent a bad request (validation/contract failure)
    - upstream : Player2 or its model failed (unreachable, slow, empty completion)
    - bridge   : an unexpected error in our own code (a real bug to fix)
    - ok       : succeeded / accepted
    """
    sm = (source_mod or "").lower()
    s = (status or "").lower()
    e = (error or "").lower()
    if any(t in sm for t in _TEST_MOD_MARKERS):
        return "test"
    if s in ("ok", "accepted") and not e:
        return "ok"
    if s == "invalid" or any(m in e for m in _CLIENT_ERROR_MARKERS):
        return "client"
    if any(m in e for m in _UPSTREAM_ERROR_MARKERS):
        return "upstream"
    if e:
        return "bridge"
    return "ok"


class BridgeTelemetry:
    """SQLite-backed telemetry for bridge traffic, errors, and Player2 probes."""

    def __init__(self, db_path: Path):
        self.db_path = db_path
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._writes = 0
        self._init_db()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=15)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.executescript(
                """
                pragma journal_mode = wal;
                create table if not exists bridge_events (
                  id integer primary key autoincrement,
                  ts_ms integer not null,
                  kind text not null,
                  request_id text,
                  source_mod text,
                  channel text,
                  status text,
                  latency_ms integer,
                  error text,
                  payload_json text
                );
                create index if not exists idx_bridge_events_ts on bridge_events(ts_ms desc);
                create index if not exists idx_bridge_events_request on bridge_events(request_id);

                create table if not exists bridge_requests (
                  request_id text primary key,
                  source_mod text not null,
                  channel text not null,
                  status text not null,
                  created_ms integer not null,
                  updated_ms integer not null,
                  latency_ms integer,
                  error text,
                  request_json text not null,
                  response_json text
                );

                create table if not exists player2_probes (
                  id integer primary key autoincrement,
                  ts_ms integer not null,
                  name text not null,
                  method text not null,
                  path text not null,
                  ok integer not null,
                  status_code integer,
                  latency_ms integer,
                  error text,
                  response_json text
                );
                create index if not exists idx_player2_probes_ts on player2_probes(ts_ms desc);
                """
            )

    def record_event(
        self,
        kind: str,
        *,
        request_id: str | None = None,
        source_mod: str | None = None,
        channel: str | None = None,
        status: str | None = None,
        latency_ms: int | None = None,
        error: str | None = None,
        payload: dict[str, Any] | None = None,
    ) -> None:
        with self._connect() as conn:
            conn.execute(
                """
                insert into bridge_events
                  (ts_ms, kind, request_id, source_mod, channel, status, latency_ms, error, payload_json)
                values (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    utc_ms(),
                    kind,
                    request_id,
                    source_mod,
                    channel,
                    status,
                    latency_ms,
                    error,
                    json.dumps(payload or {}, ensure_ascii=False),
                ),
            )
            self._writes += 1
            if self._writes % 250 == 0:
                self._prune(conn)

    def record_request(self, request: Any) -> None:
        data = request.to_dict()
        with self._connect() as conn:
            conn.execute(
                """
                insert into bridge_requests
                  (request_id, source_mod, channel, status, created_ms, updated_ms, request_json)
                values (?, ?, ?, ?, ?, ?, ?)
                on conflict(request_id) do update set
                  status=excluded.status,
                  updated_ms=excluded.updated_ms,
                  request_json=excluded.request_json
                """,
                (
                    request.request_id,
                    request.source_mod,
                    request.channel,
                    "accepted",
                    utc_ms(),
                    utc_ms(),
                    json.dumps(data, ensure_ascii=False),
                ),
            )
        self.record_event(
            "request.accepted",
            request_id=request.request_id,
            source_mod=request.source_mod,
            channel=request.channel,
            status="accepted",
            payload=data,
        )

    def record_response(self, response: dict[str, Any]) -> None:
        request_id = str(response.get("request_id") or "")
        with self._connect() as conn:
            conn.execute(
                """
                update bridge_requests
                set status=?, updated_ms=?, latency_ms=?, error=?, response_json=?
                where request_id=?
                """,
                (
                    response.get("status"),
                    utc_ms(),
                    response.get("latency_ms"),
                    response.get("error"),
                    json.dumps(response, ensure_ascii=False),
                    request_id,
                ),
            )
        self.record_event(
            "request.completed",
            request_id=request_id,
            source_mod=response.get("source_mod"),
            channel=response.get("channel"),
            status=response.get("status"),
            latency_ms=response.get("latency_ms"),
            error=response.get("error"),
            payload=response,
        )

    def record_probe(
        self,
        name: str,
        method: str,
        path: str,
        ok: bool,
        *,
        status_code: int | None = None,
        latency_ms: int | None = None,
        error: str | None = None,
        response: dict[str, Any] | None = None,
    ) -> None:
        with self._connect() as conn:
            conn.execute(
                """
                insert into player2_probes
                  (ts_ms, name, method, path, ok, status_code, latency_ms, error, response_json)
                values (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    utc_ms(),
                    name,
                    method,
                    path,
                    1 if ok else 0,
                    status_code,
                    latency_ms,
                    error,
                    json.dumps(response or {}, ensure_ascii=False),
                ),
            )

    # Keep telemetry bounded so a long session never grows without limit.
    MAX_EVENTS = 5000
    MAX_REQUESTS = 3000
    MAX_PROBES = 2000

    def _prune(self, conn: sqlite3.Connection) -> None:
        conn.execute(
            "delete from bridge_events where id not in "
            "(select id from bridge_events order by ts_ms desc limit ?)", (self.MAX_EVENTS,))
        conn.execute(
            "delete from bridge_requests where request_id not in "
            "(select request_id from bridge_requests order by updated_ms desc limit ?)", (self.MAX_REQUESTS,))
        conn.execute(
            "delete from player2_probes where id not in "
            "(select id from player2_probes order by ts_ms desc limit ?)", (self.MAX_PROBES,))

    def clear(self) -> dict[str, Any]:
        """Wipe all telemetry so the dashboard reflects only current traffic."""
        with self._connect() as conn:
            conn.executescript(
                "delete from bridge_events; delete from bridge_requests; delete from player2_probes;")
            conn.execute("vacuum")
        return {"ok": True, "cleared": "telemetry"}

    def snapshot(self, limit: int = 100) -> dict[str, Any]:
        with self._connect() as conn:
            counts = dict(
                conn.execute(
                    """
                    select
                      count(*) as total,
                      sum(case when status='ok' then 1 else 0 end) as ok,
                      sum(case when status='degraded' then 1 else 0 end) as degraded,
                      sum(case when error is not null and error != '' then 1 else 0 end) as errors
                    from bridge_requests
                    """
                ).fetchone()
            )
            counts = {key: (0 if value is None else value) for key, value in counts.items()}
            events = [dict(row) for row in conn.execute(
                """
                select id, ts_ms, kind, request_id, source_mod, channel, status, latency_ms, error
                from bridge_events
                order by ts_ms desc
                limit ?
                """,
                (limit,),
            )]
            requests = [dict(row) for row in conn.execute(
                "select request_id, source_mod, channel, status, created_ms, updated_ms, latency_ms, error from bridge_requests order by updated_ms desc limit ?",
                (limit,),
            )]
            probes = [dict(row) for row in conn.execute(
                """
                select id, ts_ms, name, method, path, ok, status_code, latency_ms, error
                from player2_probes
                order by ts_ms desc
                limit ?
                """,
                (limit,),
            )]
        # Tag every event/request with its fault source so the UI shows whose problem
        # it is, and roll up source counts for an at-a-glance health read.
        source_counts: dict[str, int] = {}
        for row in events:
            row["source"] = classify_source(row.get("status"), row.get("error"), row.get("source_mod"))
            source_counts[row["source"]] = source_counts.get(row["source"], 0) + 1
        for row in requests:
            row["source"] = classify_source(row.get("status"), row.get("error"), row.get("source_mod"))
        # "Real" (non-test) faults are the ones that matter for backend confidence.
        real_faults = sum(1 for r in events if r["source"] in ("client", "upstream", "bridge"))
        bridge_faults = sum(1 for r in events if r["source"] == "bridge")
        return {
            "counts": counts,
            "source_counts": source_counts,
            "real_faults": real_faults,
            "bridge_faults": bridge_faults,
            "events": events,
            "requests": requests,
            "player2_probes": probes,
            "db_path": str(self.db_path),
            "db_state": self.db_state(),
        }

    def db_state(self) -> dict[str, Any]:
        wal_path = self.db_path.with_name(f"{self.db_path.name}-wal")
        shm_path = self.db_path.with_name(f"{self.db_path.name}-shm")
        with self._connect() as conn:
            tables = {}
            latest_columns = {
                "bridge_events": "ts_ms",
                "bridge_requests": "updated_ms",
                "player2_probes": "ts_ms",
            }
            for table, latest_column in latest_columns.items():
                row = conn.execute(f"select count(*) as rows from {table}").fetchone()
                latest = conn.execute(
                    f"select max({latest_column}) as latest_ms from {table}"
                ).fetchone()
                tables[table] = {
                    "rows": int(row["rows"] or 0),
                    "latest_ms": latest["latest_ms"],
                }
        return {
            "path": str(self.db_path),
            "bytes": self.db_path.stat().st_size if self.db_path.exists() else 0,
            "wal_bytes": wal_path.stat().st_size if wal_path.exists() else 0,
            "shm_bytes": shm_path.stat().st_size if shm_path.exists() else 0,
            "tables": tables,
        }

    def request_detail(self, request_id: str) -> dict[str, Any] | None:
        with self._connect() as conn:
            row = conn.execute(
                "select * from bridge_requests where request_id = ?",
                (request_id,),
            ).fetchone()
        return self._decode_row(row) if row else None

    def event_detail(self, event_id: int) -> dict[str, Any] | None:
        with self._connect() as conn:
            row = conn.execute("select * from bridge_events where id = ?", (event_id,)).fetchone()
        return self._decode_row(row) if row else None

    def probe_detail(self, probe_id: int) -> dict[str, Any] | None:
        with self._connect() as conn:
            row = conn.execute("select * from player2_probes where id = ?", (probe_id,)).fetchone()
        return self._decode_row(row) if row else None

    @staticmethod
    def _decode_row(row: sqlite3.Row) -> dict[str, Any]:
        data = dict(row)
        for key in ("payload_json", "request_json", "response_json"):
            if key in data and data[key]:
                try:
                    data[key.removesuffix("_json")] = json.loads(data[key])
                except Exception:
                    data[key.removesuffix("_json")] = data[key]
                del data[key]
        return data
